#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (C) 2013 Osmo Salomaa
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
Print compact information about a video file to standard output.

Requires ffprobe from ffmpeg.
"""

import locale
import os
import subprocess
import sys

container = []
streams = []


def calculate_bitrates():
    """
    Try to fill in missing bitrate information.

    If ffprobe fails to detect the bitrate of just one track, we can calculate
    that by subtracting bitrates of known tracks from the total bitrate of the
    whole file. Considering only audio and video tracks, there will be a small
    error since the space used by subtitles and the container metadata are not
    accounted for in these calculations.
    """
    total = sum(float(x["bit_rate"]) for x in container)
    astreams = [x for x in streams if x["codec_type"] == "audio"]
    vstreams = [x for x in streams if x["codec_type"] == "video"]
    known = 0
    for entry in astreams + vstreams:
        entry["bit_rate_fuzzy"] = (entry["bit_rate"] == "N/A")
        if not entry["bit_rate_fuzzy"]:
            known += float(entry["bit_rate"])
    nmissing = sum(x["bit_rate_fuzzy"]for x in astreams + vstreams)
    if nmissing > 1: return
    for entry in astreams + vstreams:
        if entry["bit_rate_fuzzy"]:
            entry["bit_rate"] = str(int(total - known))

def comma_print(x):
    """Print `x` with a leading comma."""
    return print0("; {}".format(x))

def main(path):
    """Print information to standard output."""
    read_output(("ffprobe", "-show_format", path), container)
    read_output(("ffprobe", "-show_streams", path), streams)
    calculate_bitrates()
    print_general(path)
    print_video(path)
    print_audio(path)
    print_subtitles(path)

def print0(x):
    """Print `x` without a trailing newline."""
    return print(x, end="")

def print_audio(path):
    """Print audio track information."""
    astreams = [x for x in streams if x["codec_type"] == "audio"]
    for i, entry in enumerate(astreams):
        print0("Audio: ")
        format = entry["codec_tag_string"].lower()
        if format.find("[0]") > -1:
            format = entry["codec_name"]
        print0(format)
        bitrate = entry["bit_rate"]
        if bitrate != "N/A":
            bitrate = float(bitrate) / 1000
            bitrate = "{:.0f} kbps".format(bitrate)
            if entry["bit_rate_fuzzy"]:
                bitrate = "~" + bitrate
            comma_print(bitrate)
        channels = "{} channels".format(entry["channels"])
        channels = channels.replace("1 channels", "1 channel")
        comma_print(channels)
        if "TAG:language" in entry:
            if entry["TAG:language"] != "und":
                comma_print(entry["TAG:language"])
        print0("\n")

def print_general(path):
    """Print general information."""
    print(os.path.basename(path))
    for entry in container:
        print0(entry["format_name"])
        size = os.stat(path)[6] / 1024**2
        comma_print("{:.0f} MB".format(size))
        duration = float(entry["duration"])
        comma_print(seconds_to_time(duration))
        bitrate = float(entry["bit_rate"]) / 1000
        comma_print("{:.0f} kbps".format(bitrate))
        print0("\n")

def print_subtitles(path):
    """Print subtitle track information."""
    sstreams = [x for x in streams if x["codec_type"] == "subtitle"]
    for i, entry in enumerate(sstreams):
        print0("Subtitles: ")
        format = entry["codec_tag_string"].lower()
        if format.find("[0]") > -1:
            format = entry["codec_name"]
        print0(format)
        if "TAG:language" in entry:
            if entry["TAG:language"] != "und":
                comma_print(entry["TAG:language"])
        print0("\n")

def print_video(path):
    """Print video track information."""
    vstreams = [x for x in streams if x["codec_type"] == "video"]
    for i, entry in enumerate(vstreams):
        print0("Video: ")
        format = entry["codec_tag_string"].lower()
        if format.find("[0]") > -1:
            format = entry["codec_name"]
        print0(format)
        bitrate = entry["bit_rate"]
        if bitrate != "N/A":
            bitrate = float(bitrate) / 1000
            bitrate = "{:.0f} kbps".format(bitrate)
            if entry["bit_rate_fuzzy"]:
                bitrate = "~" + bitrate
            comma_print(bitrate)
        ratio = split_field(entry["display_aspect_ratio"], ":", int)
        resolution = ("{:d}x{:d} @ dar {:.2f}"
                      .format(int(entry["width"]),
                              int(entry["height"]),
                              ratio[0]/ratio[1]))

        comma_print(resolution)
        framerate = split_field(entry["r_frame_rate"], "/", int)
        comma_print("{:.3f} fps".format(framerate[0]/framerate[1]))
        print0("\n")

def read_output(command, dst):
    """Read output from `command` to `dst`."""
    process = subprocess.Popen(command,
                               stderr=subprocess.PIPE,
                               stdout=subprocess.PIPE)

    output = process.communicate()[0]
    encoding = locale.getpreferredencoding(do_setlocale=False)
    output = output.decode(encoding, errors="replace")
    for line in output.splitlines():
        if line.startswith("["):
            if not line.startswith("[/"):
                dst.append({})
        elif "=" in line:
            field, value = line.split("=", 1)
            dst[-1][field] = value

def seconds_to_time(seconds):
    """Convert `seconds` to a time string."""
    return ("{:02.0f}:{:02.0f}:{:02.0f}"
            .format(seconds // 3600,
                    (seconds % 3600) // 60,
                    seconds % 60))

def split_field(value, separator, fun=None):
    """Split `value` by `separator` and apply `fun`."""
    value = value.split(separator, 2)
    if fun is not None:
        value = [fun(x) for x in value]
    return value


if __name__ == "__main__":
    if not sys.argv[1:]:
        raise SystemExit("Usage: ffinfo FILE")
    main(sys.argv[1])
